# .streamlit/secrets.toml

ALCHEMY_KEY = "dy--ZGxDrBX-uYATHrBqiWcGXDs32XP0"
COVALENT_KEY = "your_covalent_api_key_here"
OPENROUTER_KEY = ""
TELEGRAM_TOKEN = "7653839390:AAGBLb8XkBxep9EaIo0wEX4Nu-dU8JlOSAk"
TELEGRAM_CHAT_ID = "6913117009"
FERNET_KEY = "kdMG7ARjqfMfTm58dGzwv2UOyyAHuTZg58-Sk_26VdY="